name: 'diplom_boichuk_bohdan'
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  package_info_plus: ^1.4.3+1
  easy_localization: 3.0.1
  logger: ^1.1.0
  flutter_modular: ^5.0.3
  hexcolor: ^2.0.7
  flutter_svg: ^1.0.3
  string_validator: ^0.3.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.6
  uni_links: ^0.5.1
  phone_number: ^1.0.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_link_previewer: ^3.2.0
  flutter_parsed_text: ^2.2.1
  flutter_slidable: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ff_stars: ^3.0.0
  permission_handler: ^10.2.0
  dash_flags: ^0.0.3
  getwidget: ^3.1.1
  audio_waveforms: ^1.0.4
  animated_text_kit: ^4.2.2
  audio_session: ^0.1.14
  path_provider: ^2.0.15
  flutter_sound: ^9.2.13
  file_picker: ^5.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.4.0
  hive_generator: ^2.0.0
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/svg/

